// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0
// source: pkg/proto/caseItems.proto

package proto1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemName        string `protobuf:"bytes,2,opt,name=itemName,proto3" json:"itemName,omitempty"`
	ItemDescription string `protobuf:"bytes,3,opt,name=itemDescription,proto3" json:"itemDescription,omitempty"`
	Type            string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Stars           int64  `protobuf:"varint,5,opt,name=stars,proto3" json:"stars,omitempty"`
	Image           []byte `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *CaseItem) Reset() {
	*x = CaseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_caseItems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseItem) ProtoMessage() {}

func (x *CaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_caseItems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseItem.ProtoReflect.Descriptor instead.
func (*CaseItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_caseItems_proto_rawDescGZIP(), []int{0}
}

func (x *CaseItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CaseItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CaseItem) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

func (x *CaseItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CaseItem) GetStars() int64 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *CaseItem) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type Confirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Confirm) Reset() {
	*x = Confirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_caseItems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirm) ProtoMessage() {}

func (x *Confirm) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_caseItems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirm.ProtoReflect.Descriptor instead.
func (*Confirm) Descriptor() ([]byte, []int) {
	return file_pkg_proto_caseItems_proto_rawDescGZIP(), []int{1}
}

func (x *Confirm) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Confirm) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CaseItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CaseItemRequest) Reset() {
	*x = CaseItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_caseItems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseItemRequest) ProtoMessage() {}

func (x *CaseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_caseItems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseItemRequest.ProtoReflect.Descriptor instead.
func (*CaseItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_caseItems_proto_rawDescGZIP(), []int{2}
}

func (x *CaseItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CaseItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CaseItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseItems []*CaseItem `protobuf:"bytes,1,rep,name=CaseItems,proto3" json:"CaseItems,omitempty"`
}

func (x *CaseItems) Reset() {
	*x = CaseItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_caseItems_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseItems) ProtoMessage() {}

func (x *CaseItems) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_caseItems_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseItems.ProtoReflect.Descriptor instead.
func (*CaseItems) Descriptor() ([]byte, []int) {
	return file_pkg_proto_caseItems_proto_rawDescGZIP(), []int{3}
}

func (x *CaseItems) GetCaseItems() []*CaseItem {
	if x != nil {
		return x.CaseItems
	}
	return nil
}

var File_pkg_proto_caseItems_proto protoreflect.FileDescriptor

var file_pkg_proto_caseItems_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x73, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x61, 0x73,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x35, 0x0a,
	0x0f, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x30, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x32, 0x81, 0x02, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x73,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x2e, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x11, 0x2e, 0x63, 0x61, 0x73, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x00, 0x12, 0x39,
	0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x12, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x61, 0x73, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x1a, 0x11, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c, 0x53, 0x68, 0x6f,
	0x77, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x73, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x11, 0x2e,
	0x63, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x1a, 0x13, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x61, 0x73, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_caseItems_proto_rawDescOnce sync.Once
	file_pkg_proto_caseItems_proto_rawDescData = file_pkg_proto_caseItems_proto_rawDesc
)

func file_pkg_proto_caseItems_proto_rawDescGZIP() []byte {
	file_pkg_proto_caseItems_proto_rawDescOnce.Do(func() {
		file_pkg_proto_caseItems_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_caseItems_proto_rawDescData)
	})
	return file_pkg_proto_caseItems_proto_rawDescData
}

var file_pkg_proto_caseItems_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_caseItems_proto_goTypes = []interface{}{
	(*CaseItem)(nil),        // 0: caseItem.CaseItem
	(*Confirm)(nil),         // 1: caseItem.Confirm
	(*CaseItemRequest)(nil), // 2: caseItem.CaseItemRequest
	(*CaseItems)(nil),       // 3: caseItem.CaseItems
}
var file_pkg_proto_caseItems_proto_depIdxs = []int32{
	0, // 0: caseItem.CaseItems.CaseItems:type_name -> caseItem.CaseItem
	0, // 1: caseItem.UserService.CreateCaseItem:input_type -> caseItem.CaseItem
	0, // 2: caseItem.UserService.DeleteCaseItem:input_type -> caseItem.CaseItem
	2, // 3: caseItem.UserService.ShowCaseItem:input_type -> caseItem.CaseItemRequest
	1, // 4: caseItem.UserService.GetAllCaseItems:input_type -> caseItem.Confirm
	1, // 5: caseItem.UserService.CreateCaseItem:output_type -> caseItem.Confirm
	1, // 6: caseItem.UserService.DeleteCaseItem:output_type -> caseItem.Confirm
	0, // 7: caseItem.UserService.ShowCaseItem:output_type -> caseItem.CaseItem
	3, // 8: caseItem.UserService.GetAllCaseItems:output_type -> caseItem.CaseItems
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_caseItems_proto_init() }
func file_pkg_proto_caseItems_proto_init() {
	if File_pkg_proto_caseItems_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_caseItems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_caseItems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_caseItems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_caseItems_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_caseItems_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_caseItems_proto_goTypes,
		DependencyIndexes: file_pkg_proto_caseItems_proto_depIdxs,
		MessageInfos:      file_pkg_proto_caseItems_proto_msgTypes,
	}.Build()
	File_pkg_proto_caseItems_proto = out.File
	file_pkg_proto_caseItems_proto_rawDesc = nil
	file_pkg_proto_caseItems_proto_goTypes = nil
	file_pkg_proto_caseItems_proto_depIdxs = nil
}
